nowplaying: add shamiradio option
bakape/meguca pull request #1249
Opened 2020-11-10 11:05 UTC by Kamuso

2020-11-10 19:28 UTC, bakape requested changes

2020-11-10 19:28 UTC, bakape commented on client/options/nowPlaying.ts
> +		urlBase: 'https://radio.shamik.ooo/',
I'd like to avoid hardcoding the domain as much as possible. Please make this a server config.

2020-11-10 19:28 UTC, bakape commented on client/options/index.ts
> +	shami: boolean
Make the key name more generic, please.

2020-11-10 19:28 UTC, bakape commented on static/src/lang/en_GB/server.json
> +			"shamiradio",
Same for all translations.

2020-11-10 19:28 UTC, bakape commented on client/options/index.ts
> +	shami: boolean
Maybe something like `customRadio`.

2020-11-10 19:43 UTC, Kamuso commented
I don't think making it more generic is correct, since  it is specifically the shamiko radio. The underlying radio isn't related to the meguca software, it just happens to use the same domain. It's not a meguca(tm) radio, it's a radio hosted on shamik.ooo. Do you get what I mean?

2020-11-12 17:23 UTC, bakape commented
Okay, fair point.

On Tue, 10 Nov 2020 at 21:43, Kamuso <notifications@github.com> wrote:

> I don't think making it more generic is correct, since it is specifically
> the shamiko radio. The underlying radio isn't related to the meguca
> software, it just happens to use the same domain. It's not a meguca(tm)
> radio, it's a radio hosted on shamik.ooo. Do you get what I mean?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bakape/meguca/pull/1249#issuecomment-724925135>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB347MAWYS5ZLA6FGAKGGH3SPGJXVANCNFSM4TQQOR3Q>
> .
>

2020-11-12 17:23 UTC, merged